<a href="https://colab.research.google.com/github/rizzaesh/Thesis---a-two-layer-power-network/blob/main/pandapower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [14]:
A = np.array([[1,1,1,0,0],[0,0,-1,1,-1]])
b = np.array([0,0,0])

In [9]:
A

array([[ 1,  1,  1,  0,  0],
       [ 0,  0, -1,  1, -1]])

In [12]:
b

array([0, 0])

In [ ]:
c = np.linalg.solve(A,b)

In [ ]:
a = np.array([[1,5 ,6], [3, 5,2]])
b = np.array([1,1 ,5])
x = np.linalg.solve(a, b)
x

In [44]:
a = np.eye(2*3*4)
a.shape = (2*3, 4, 2, 3, 4)
b = np.random.randn(2*3, 4)
# a = np.array([[1,5 ,6], [3, 5,2]])
# b = np.array([1,1 ,5])
x = np.linalg.tensorsolve(a, b)
x.shape

(2, 3, 4)

In [46]:
R = np.matrix('50 0 -30; 0 40 -20; -30 -20 100')
V = np.matrix('80; 80; 0')
I = np.linalg.inv(R) * V
print(I)

[[2.33333333]
 [2.61111111]
 [1.22222222]]


In [ ]:
pip install pandapower

In [11]:
from pandapower.auxiliary import *
from pandapower.convert_format import *
from pandapower.create import *
from pandapower.diagnostic import *
from pandapower.file_io import *
from pandapower.run import *
from pandapower.runpm import *
from pandapower.std_types import *
from pandapower.toolbox import *
from pandapower.powerflow import *
from pandapower.opf import *
from pandapower.optimal_powerflow import OPFNotConverged
from pandapower.pf.runpp_3ph import runpp_3ph
import pandas as pd

In [10]:
pandapower.create_line(from_bus=1,to_bus=3)

TypeError: ignored